workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      when: always
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
      when: always

stages:
  - cache
  - lint
  - build
  - test

include:
  - ci/templates.yml
  - ci/bindings.yml
  - ci/caching.yml
  - ci/repo.yml
  - ci/safe-stage.yml
