workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      when: always
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
      when: always

stages:
  - cache
  - lint
  - build
  - test

include:
  - .gitlab/templates.yml
  - .gitlab/bindings.yml
  - .gitlab/caching.yml
  - .gitlab/repo.yml
  - .gitlab/safe-stage.yml
  - .gitlab/service-app.yml
