[workspace]
resolver = "2"
members = [
    "collisioner",
    "mather",
    "service-app/src-tauri"
]

[workspace.dependencies]
rusty-hook = "0.11.2"
assert_float_eq = "1.1.3"
pretty_assertions = "1.4.0"
serde = "1.0.193"
