[package]
name = "mather"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }

[dev-dependencies]
assert_float_eq = "1.1.3"
pretty_assertions = "1.4.0"
