[package]
name = "mather"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
assert_float_eq.workspace = true
pretty_assertions.workspace = true
