[profile.ci-default]
fail-fast = false

[profile.ci-default.junit]
report-name = "nextest-default"
path = "junit-report.xml"
store-success-output = true
store-failure-output = true


[profile.ci-features-ffi.junit]
report-name = "nextest-features-ffi"
path = "junit-report.xml"
store-success-output = true
store-failure-output = true

[profile.default-miri.junit]
report-name = "nextest-miri"
path = "junit-report.xml"
store-success-output = true
store-failure-output = true
