[graph]
targets = [
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
]

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

[licenses]
confidence-threshold = 0.9
private = { ignore = true }
allow = ["Apache-2.0", "MIT", "Unicode-3.0"]
exceptions = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
