name: Build and Release Service Application
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  service-app-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup default stable

      - name: Add cargo-expand
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-expand

      - name: Build Safe Stage
        run: |
          cargo run -p bindings
          cargo build --release --features ffi
        working-directory: ./safe-stage

      - name: Publish Service Application
        run: |
          dotnet publish
        working-directory: ./service-app

      - name: Archive Publish Directory
        run: Compress-Archive -Path service-app/ServiceApp/bin/Release/net8.0-windows/publish/* -DestinationPath service-app.zip

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "service-app.zip"
          draft: true
