name: Build Service Application
on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  service-app-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        run: rustup default stable

      - name: Add cargo-expand
        run: cargo install cargo-expand

      - name: Build Safe Stage
        run: |
          cd ./safe-stage
          cargo run -p bindings
          cargo build --release -F ffi

      - name: Build Service Application
        run: |
          cd ./service-app
          dotnet build
