name: Build Service Application
on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

env:
  CARGO_TERM_COLOR: always

jobs:
  service-app-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./safe-stage/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Set up Rust
        run: rustup default stable

      - name: Add cargo-expand
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: cargo install cargo-expand

      - name: Build Safe Stage
        run: |
          cargo run -p bindings
          cargo build --release -F ffi
        working-directory: ./safe-stage

      - name: Build Service Application
        run: |
          dotnet build
        working-directory: ./service-app
